apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openrtb-bidder-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10"
    nginx.ingress.kubernetes.io/keep-alive-requests: "100000"
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "256"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "60"
    nginx.ingress.kubernetes.io/upstream-keepalive-requests: "100000"
spec:
  rules:
  - host: bidder.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openrtb-bidder-service
            port:
              number: 80

